/*
"How efficient is our delivery process across different regions?"
Why this matters: Identify operational bottlenecks and regional performance variations.

What are analyzed:

Average delivery time by state,
On-time delivery performance
Freight cost analysis
*/


SELECT
    customers.customer_state,
    customers.customer_city,
    ROUND(AVG(EXTRACT(DAY FROM (orders.order_delivered_customer_date - orders.order_purchase_timestamp))),0) AS avg_delivery_time_days,
    ROUND(AVG(EXTRACT(DAY FROM (orders.order_estimated_delivery_date - orders.order_delivered_customer_date))),0) AS avg_days_early_positive_late_negative,
    ROUND(COUNT(CASE WHEN orders.order_delivered_customer_date <= orders.order_estimated_delivery_date THEN 1 END) * 100.0 / COUNT(orders.order_id), 0) AS on_time_delivery_percentage,
    ROUND(AVG(order_items.freight_value),0) AS avg_freight_cost,
    ROUND(SUM(order_items.freight_value),0)AS total_freight_revenue,
    COUNT(orders.order_id) AS total_orders,
    COUNT(DISTINCT customers.customer_id) AS unique_customers
FROM customers
    INNER JOIN orders ON customers.customer_id = orders.customer_id
    INNER JOIN order_items ON orders.order_id = order_items.order_id
WHERE orders.order_delivered_customer_date IS NOT NULL
GROUP BY
    customers.customer_state, customers.customer_city
ORDER BY
    avg_delivery_time_days ASC;


/* Insights:
1. Major states like SP and RJ have the slowest delivery (7-14 days) but generate the most revenue, highlighting a speed-volume trade-off.
2. Reliability over Speed: The network prioritizes predictability, achieving >94% on-time delivery even in its slowest, high-value regions.
3. Cost ≠ Speed: Higher freight costs don't guarantee faster delivery, suggesting costs are tied to remoteness, not service speed.
4. States like SC and PR show the ideal balance: fast (4-6 days), 100% on-time, and cost-effective delivery.
5. Strategic Vulnerability: Heavy revenue dependence on a few slow-delivery states creates significant operational and financial risk.

Recommendation:
1. Optimize logistics in high-revenue but slow states (SP, RJ) to reduce delivery times without sacrificing reliability.
2. Replicate efficient practices from fast, reliable states (SC, PR) in slower regions.
3. Negotiate better freight rates in high-cost states to improve margins.

Result Set:

[
  {
    "customer_state": "SC",
    "customer_city": "iomere",
    "avg_delivery_time_days": "2",
    "avg_days_early_positive_late_negative": "11",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "15",
    "total_freight_revenue": "15",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "bento de abreu",
    "avg_delivery_time_days": "3",
    "avg_days_early_positive_late_negative": "18",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "15",
    "total_freight_revenue": "44",
    "total_orders": "3",
    "unique_customers": "2"
  },
  {
    "customer_state": "PR",
    "customer_city": "contenda",
    "avg_delivery_time_days": "3",
    "avg_days_early_positive_late_negative": "9",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "15",
    "total_freight_revenue": "15",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "PE",
    "customer_city": "siriji",
    "avg_delivery_time_days": "3",
    "avg_days_early_positive_late_negative": "24",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "37",
    "total_freight_revenue": "37",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "MG",
    "customer_city": "acucena",
    "avg_delivery_time_days": "3",
    "avg_days_early_positive_late_negative": "17",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "16",
    "total_freight_revenue": "16",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "pedra bela",
    "avg_delivery_time_days": "4",
    "avg_days_early_positive_late_negative": "10",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "14",
    "total_freight_revenue": "28",
    "total_orders": "2",
    "unique_customers": "2"
  },
  {
    "customer_state": "SP",
    "customer_city": "piquerobi",
    "avg_delivery_time_days": "4",
    "avg_days_early_positive_late_negative": "9",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "27",
    "total_freight_revenue": "27",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "RN",
    "customer_city": "sitio novo",
    "avg_delivery_time_days": "4",
    "avg_days_early_positive_late_negative": "26",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "20",
    "total_freight_revenue": "20",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "MG",
    "customer_city": "delfim moreira",
    "avg_delivery_time_days": "4",
    "avg_days_early_positive_late_negative": "34",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "14",
    "total_freight_revenue": "14",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "embauba",
    "avg_delivery_time_days": "4",
    "avg_days_early_positive_late_negative": "13",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "16",
    "total_freight_revenue": "16",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "GO",
    "customer_city": "sao patricio",
    "avg_delivery_time_days": "4",
    "avg_days_early_positive_late_negative": "21",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "14",
    "total_freight_revenue": "14",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "RS",
    "customer_city": "sao joao da urtiga",
    "avg_delivery_time_days": "4",
    "avg_days_early_positive_late_negative": "20",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "17",
    "total_freight_revenue": "17",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "planalto",
    "avg_delivery_time_days": "4",
    "avg_days_early_positive_late_negative": "13",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "13",
    "total_freight_revenue": "13",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "RJ",
    "customer_city": "barao de juparana",
    "avg_delivery_time_days": "4",
    "avg_days_early_positive_late_negative": "22",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "18",
    "total_freight_revenue": "18",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "MG",
    "customer_city": "divino das laranjeiras",
    "avg_delivery_time_days": "4",
    "avg_days_early_positive_late_negative": "12",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "15",
    "total_freight_revenue": "15",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "RS",
    "customer_city": "cambara do sul",
    "avg_delivery_time_days": "4",
    "avg_days_early_positive_late_negative": "16",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "14",
    "total_freight_revenue": "29",
    "total_orders": "2",
    "unique_customers": "1"
  },
  {
    "customer_state": "MG",
    "customer_city": "frei gaspar",
    "avg_delivery_time_days": "4",
    "avg_days_early_positive_late_negative": "13",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "14",
    "total_freight_revenue": "14",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "RJ",
    "customer_city": "anta",
    "avg_delivery_time_days": "4",
    "avg_days_early_positive_late_negative": "20",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "17",
    "total_freight_revenue": "50",
    "total_orders": "3",
    "unique_customers": "3"
  },
  {
    "customer_state": "SC",
    "customer_city": "agua doce",
    "avg_delivery_time_days": "4",
    "avg_days_early_positive_late_negative": "15",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "23",
    "total_freight_revenue": "46",
    "total_orders": "2",
    "unique_customers": "1"
  },
  {
    "customer_state": "RS",
    "customer_city": "miraguai",
    "avg_delivery_time_days": "5",
    "avg_days_early_positive_late_negative": "14",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "13",
    "total_freight_revenue": "13",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "MS",
    "customer_city": "caracol",
    "avg_delivery_time_days": "5",
    "avg_days_early_positive_late_negative": "16",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "17",
    "total_freight_revenue": "17",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "PR",
    "customer_city": "sao carlos do ivai",
    "avg_delivery_time_days": "5",
    "avg_days_early_positive_late_negative": "23",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "27",
    "total_freight_revenue": "27",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SC",
    "customer_city": "guaraciaba",
    "avg_delivery_time_days": "5",
    "avg_days_early_positive_late_negative": "21",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "18",
    "total_freight_revenue": "18",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "guapiara",
    "avg_delivery_time_days": "5",
    "avg_days_early_positive_late_negative": "16",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "14",
    "total_freight_revenue": "42",
    "total_orders": "3",
    "unique_customers": "3"
  },
  {
    "customer_state": "PI",
    "customer_city": "sao miguel do tapuio",
    "avg_delivery_time_days": "5",
    "avg_days_early_positive_late_negative": "11",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "30",
    "total_freight_revenue": "60",
    "total_orders": "2",
    "unique_customers": "2"
  },
  {
    "customer_state": "SP",
    "customer_city": "nantes",
    "avg_delivery_time_days": "5",
    "avg_days_early_positive_late_negative": "14",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "12",
    "total_freight_revenue": "12",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "CE",
    "customer_city": "barreira",
    "avg_delivery_time_days": "5",
    "avg_days_early_positive_late_negative": "16",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "18",
    "total_freight_revenue": "18",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "MG",
    "customer_city": "sao francisco do gloria",
    "avg_delivery_time_days": "5",
    "avg_days_early_positive_late_negative": "15",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "21",
    "total_freight_revenue": "21",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "MG",
    "customer_city": "antonio carlos",
    "avg_delivery_time_days": "5",
    "avg_days_early_positive_late_negative": "23",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "18",
    "total_freight_revenue": "18",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "MG",
    "customer_city": "vargem alegre",
    "avg_delivery_time_days": "5",
    "avg_days_early_positive_late_negative": "12",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "20",
    "total_freight_revenue": "20",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "salto grande",
    "avg_delivery_time_days": "5",
    "avg_days_early_positive_late_negative": "14",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "34",
    "total_freight_revenue": "34",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "guarapua",
    "avg_delivery_time_days": "5",
    "avg_days_early_positive_late_negative": "27",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "15",
    "total_freight_revenue": "15",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "PR",
    "customer_city": "quitandinha",
    "avg_delivery_time_days": "5",
    "avg_days_early_positive_late_negative": "14",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "18",
    "total_freight_revenue": "36",
    "total_orders": "2",
    "unique_customers": "2"
  },
  {
    "customer_state": "SP",
    "customer_city": "inubia paulista",
    "avg_delivery_time_days": "5",
    "avg_days_early_positive_late_negative": "12",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "13",
    "total_freight_revenue": "40",
    "total_orders": "3",
    "unique_customers": "3"
  },
  {
    "customer_state": "RS",
    "customer_city": "mariano moro",
    "avg_delivery_time_days": "5",
    "avg_days_early_positive_late_negative": "32",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "12",
    "total_freight_revenue": "12",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "meridiano",
    "avg_delivery_time_days": "5",
    "avg_days_early_positive_late_negative": "6",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "21",
    "total_freight_revenue": "21",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "biritiba-mirim",
    "avg_delivery_time_days": "5",
    "avg_days_early_positive_late_negative": "18",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "17",
    "total_freight_revenue": "198",
    "total_orders": "12",
    "unique_customers": "10"
  },
  {
    "customer_state": "MG",
    "customer_city": "simao pereira",
    "avg_delivery_time_days": "5",
    "avg_days_early_positive_late_negative": "15",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "26",
    "total_freight_revenue": "26",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "mogi-mirim",
    "avg_delivery_time_days": "5",
    "avg_days_early_positive_late_negative": "16",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "11",
    "total_freight_revenue": "23",
    "total_orders": "2",
    "unique_customers": "2"
  },
  {
    "customer_state": "SP",
    "customer_city": "rifaina",
    "avg_delivery_time_days": "5",
    "avg_days_early_positive_late_negative": "12",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "22",
    "total_freight_revenue": "45",
    "total_orders": "2",
    "unique_customers": "2"
  },
  {
    "customer_state": "SP",
    "customer_city": "anhumas",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "15",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "13",
    "total_freight_revenue": "13",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "MG",
    "customer_city": "irai de minas",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "24",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "61",
    "total_freight_revenue": "122",
    "total_orders": "2",
    "unique_customers": "2"
  },
  {
    "customer_state": "BA",
    "customer_city": "taboquinhas",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "9",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "14",
    "total_freight_revenue": "14",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "marinopolis",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "13",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "15",
    "total_freight_revenue": "30",
    "total_orders": "2",
    "unique_customers": "2"
  },
  {
    "customer_state": "PR",
    "customer_city": "barra do jacare",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "13",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "14",
    "total_freight_revenue": "14",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "cajobi",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "15",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "16",
    "total_freight_revenue": "144",
    "total_orders": "9",
    "unique_customers": "8"
  },
  {
    "customer_state": "SP",
    "customer_city": "pirapora do bom jesus",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "12",
    "on_time_delivery_percentage": "94",
    "avg_freight_cost": "19",
    "total_freight_revenue": "323",
    "total_orders": "17",
    "unique_customers": "16"
  },
  {
    "customer_state": "SP",
    "customer_city": "taiacu",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "7",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "10",
    "total_freight_revenue": "10",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "MG",
    "customer_city": "pequi",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "14",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "28",
    "total_freight_revenue": "28",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "santa albertina",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "14",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "16",
    "total_freight_revenue": "144",
    "total_orders": "9",
    "unique_customers": "7"
  },
  {
    "customer_state": "SP",
    "customer_city": "ribeirao do sul",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "10",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "14",
    "total_freight_revenue": "58",
    "total_orders": "4",
    "unique_customers": "3"
  },
  {
    "customer_state": "SP",
    "customer_city": "duartina",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "12",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "17",
    "total_freight_revenue": "201",
    "total_orders": "12",
    "unique_customers": "10"
  },
  {
    "customer_state": "PB",
    "customer_city": "remigio",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "27",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "20",
    "total_freight_revenue": "20",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "MG",
    "customer_city": "corrego danta",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "22",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "16",
    "total_freight_revenue": "32",
    "total_orders": "2",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "boraceia",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "10",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "11",
    "total_freight_revenue": "11",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "MG",
    "customer_city": "moeda",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "12",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "16",
    "total_freight_revenue": "16",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "MG",
    "customer_city": "minduri",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "19",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "23",
    "total_freight_revenue": "23",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "MG",
    "customer_city": "claro dos pocoes",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "1",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "24",
    "total_freight_revenue": "24",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "saltinho",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "10",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "22",
    "total_freight_revenue": "152",
    "total_orders": "7",
    "unique_customers": "5"
  },
  {
    "customer_state": "SP",
    "customer_city": "canitar",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "11",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "15",
    "total_freight_revenue": "31",
    "total_orders": "2",
    "unique_customers": "2"
  },
  {
    "customer_state": "SP",
    "customer_city": "ibitiuva",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "10",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "13",
    "total_freight_revenue": "13",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "icem",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "13",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "14",
    "total_freight_revenue": "158",
    "total_orders": "11",
    "unique_customers": "9"
  },
  {
    "customer_state": "SP",
    "customer_city": "queiroz",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "6",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "14",
    "total_freight_revenue": "14",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "igaracu do tiete",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "14",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "12",
    "total_freight_revenue": "50",
    "total_orders": "4",
    "unique_customers": "4"
  },
  {
    "customer_state": "SP",
    "customer_city": "ilha comprida",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "29",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "14",
    "total_freight_revenue": "42",
    "total_orders": "3",
    "unique_customers": "3"
  },
  {
    "customer_state": "MG",
    "customer_city": "sao joao da ponte",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "13",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "35",
    "total_freight_revenue": "35",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "PR",
    "customer_city": "douradina",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "11",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "19",
    "total_freight_revenue": "19",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "irapua",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "15",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "14",
    "total_freight_revenue": "69",
    "total_orders": "5",
    "unique_customers": "4"
  },
  {
    "customer_state": "MG",
    "customer_city": "sao felix de minas",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "19",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "21",
    "total_freight_revenue": "21",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "santo antonio da alegria",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "18",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "14",
    "total_freight_revenue": "43",
    "total_orders": "3",
    "unique_customers": "3"
  },
  {
    "customer_state": "RS",
    "customer_city": "roca sales",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "23",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "30",
    "total_freight_revenue": "59",
    "total_orders": "2",
    "unique_customers": "2"
  },
  {
    "customer_state": "SP",
    "customer_city": "balbinos",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "13",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "14",
    "total_freight_revenue": "14",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "timburi",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "12",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "16",
    "total_freight_revenue": "48",
    "total_orders": "3",
    "unique_customers": "3"
  },
  {
    "customer_state": "RS",
    "customer_city": "herval",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "13",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "23",
    "total_freight_revenue": "23",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "jaborandi",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "8",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "13",
    "total_freight_revenue": "40",
    "total_orders": "3",
    "unique_customers": "3"
  },
  {
    "customer_state": "MG",
    "customer_city": "santo antonio do aventureiro",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "13",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "11",
    "total_freight_revenue": "11",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "estrela do norte",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "17",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "12",
    "total_freight_revenue": "37",
    "total_orders": "3",
    "unique_customers": "3"
  },
  {
    "customer_state": "SP",
    "customer_city": "nova guataporanga",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "15",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "43",
    "total_freight_revenue": "43",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "MG",
    "customer_city": "goiana",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "13",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "16",
    "total_freight_revenue": "49",
    "total_orders": "3",
    "unique_customers": "3"
  },
  {
    "customer_state": "SP",
    "customer_city": "santa maria da serra",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "13",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "13",
    "total_freight_revenue": "26",
    "total_orders": "2",
    "unique_customers": "2"
  },
  {
    "customer_state": "MG",
    "customer_city": "santa helena de minas",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "18",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "18",
    "total_freight_revenue": "55",
    "total_orders": "3",
    "unique_customers": "2"
  },
  {
    "customer_state": "MG",
    "customer_city": "braunas",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "15",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "15",
    "total_freight_revenue": "15",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "MG",
    "customer_city": "matutina",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "10",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "16",
    "total_freight_revenue": "33",
    "total_orders": "2",
    "unique_customers": "2"
  },
  {
    "customer_state": "PR",
    "customer_city": "conselheiro mairinck",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "20",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "15",
    "total_freight_revenue": "15",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "RS",
    "customer_city": "senador salgado filho",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "27",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "19",
    "total_freight_revenue": "19",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "roseira",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "16",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "13",
    "total_freight_revenue": "66",
    "total_orders": "5",
    "unique_customers": "5"
  },
  {
    "customer_state": "SP",
    "customer_city": "sao lourenco da serra",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "12",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "14",
    "total_freight_revenue": "205",
    "total_orders": "15",
    "unique_customers": "12"
  },
  {
    "customer_state": "SC",
    "customer_city": "monte castelo",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "14",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "19",
    "total_freight_revenue": "19",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "MG",
    "customer_city": "umburatiba",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "21",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "25",
    "total_freight_revenue": "25",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "MG",
    "customer_city": "ressaquinha",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "16",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "39",
    "total_freight_revenue": "39",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "MG",
    "customer_city": "arapua",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "14",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "24",
    "total_freight_revenue": "24",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "riolandia",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "15",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "24",
    "total_freight_revenue": "72",
    "total_orders": "3",
    "unique_customers": "3"
  },
  {
    "customer_state": "SP",
    "customer_city": "luiziania",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "17",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "15",
    "total_freight_revenue": "45",
    "total_orders": "3",
    "unique_customers": "3"
  },
  {
    "customer_state": "MG",
    "customer_city": "tumiritinga",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "23",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "21",
    "total_freight_revenue": "21",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "RS",
    "customer_city": "candido godoi",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "19",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "18",
    "total_freight_revenue": "106",
    "total_orders": "6",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "aruja",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "11",
    "on_time_delivery_percentage": "99",
    "avg_freight_cost": "14",
    "total_freight_revenue": "1093",
    "total_orders": "76",
    "unique_customers": "68"
  },
  {
    "customer_state": "SC",
    "customer_city": "rio rufino",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "14",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "18",
    "total_freight_revenue": "18",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "MG",
    "customer_city": "taparuba",
    "avg_delivery_time_days": "6",
    "avg_days_early_positive_late_negative": "14",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "15",
    "total_freight_revenue": "15",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "ES",
    "customer_city": "apiaca",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "18",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "17",
    "total_freight_revenue": "100",
    "total_orders": "6",
    "unique_customers": "6"
  },
  {
    "customer_state": "PR",
    "customer_city": "rondon",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "20",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "19",
    "total_freight_revenue": "56",
    "total_orders": "3",
    "unique_customers": "2"
  },
  {
    "customer_state": "SP",
    "customer_city": "poa",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "10",
    "on_time_delivery_percentage": "98",
    "avg_freight_cost": "15",
    "total_freight_revenue": "1460",
    "total_orders": "100",
    "unique_customers": "85"
  },
  {
    "customer_state": "MG",
    "customer_city": "pingo-d'agua",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "11",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "44",
    "total_freight_revenue": "44",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "MG",
    "customer_city": "piedade dos gerais",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "24",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "16",
    "total_freight_revenue": "47",
    "total_orders": "3",
    "unique_customers": "3"
  },
  {
    "customer_state": "MG",
    "customer_city": "piau",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "20",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "18",
    "total_freight_revenue": "36",
    "total_orders": "2",
    "unique_customers": "2"
  },
  {
    "customer_state": "SP",
    "customer_city": "dobrada",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "7",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "36",
    "total_freight_revenue": "71",
    "total_orders": "2",
    "unique_customers": "2"
  },
  {
    "customer_state": "SP",
    "customer_city": "mogi das cruzes",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "10",
    "on_time_delivery_percentage": "97",
    "avg_freight_cost": "15",
    "total_freight_revenue": "6472",
    "total_orders": "435",
    "unique_customers": "374"
  },
  {
    "customer_state": "SC",
    "customer_city": "sao cristovao do sul",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "14",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "18",
    "total_freight_revenue": "18",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "PE",
    "customer_city": "altinho",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "26",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "37",
    "total_freight_revenue": "37",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "PB",
    "customer_city": "sao mamede",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "21",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "51",
    "total_freight_revenue": "51",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "MG",
    "customer_city": "passa tempo",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "12",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "26",
    "total_freight_revenue": "26",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "MG",
    "customer_city": "palma",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "22",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "22",
    "total_freight_revenue": "88",
    "total_orders": "4",
    "unique_customers": "4"
  },
  {
    "customer_state": "MG",
    "customer_city": "paineiras",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "16",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "23",
    "total_freight_revenue": "23",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "aguas da prata",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "15",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "19",
    "total_freight_revenue": "229",
    "total_orders": "12",
    "unique_customers": "10"
  },
  {
    "customer_state": "MG",
    "customer_city": "nazareno",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "14",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "14",
    "total_freight_revenue": "28",
    "total_orders": "2",
    "unique_customers": "2"
  },
  {
    "customer_state": "MG",
    "customer_city": "monte alegre de minas",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "14",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "18",
    "total_freight_revenue": "89",
    "total_orders": "5",
    "unique_customers": "4"
  },
  {
    "customer_state": "SP",
    "customer_city": "valentim gentil",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "15",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "16",
    "total_freight_revenue": "47",
    "total_orders": "3",
    "unique_customers": "3"
  },
  {
    "customer_state": "PR",
    "customer_city": "porto rico",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "11",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "20",
    "total_freight_revenue": "20",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "palmares paulista",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "21",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "11",
    "total_freight_revenue": "11",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "socorro",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "15",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "14",
    "total_freight_revenue": "321",
    "total_orders": "23",
    "unique_customers": "19"
  },
  {
    "customer_state": "SP",
    "customer_city": "americana",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "10",
    "on_time_delivery_percentage": "93",
    "avg_freight_cost": "14",
    "total_freight_revenue": "3681",
    "total_orders": "257",
    "unique_customers": "216"
  },
  {
    "customer_state": "SP",
    "customer_city": "santo expedito",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "12",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "13",
    "total_freight_revenue": "13",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "monte alegre do sul",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "10",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "26",
    "total_freight_revenue": "179",
    "total_orders": "7",
    "unique_customers": "6"
  },
  {
    "customer_state": "MG",
    "customer_city": "maravilhas",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "20",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "24",
    "total_freight_revenue": "96",
    "total_orders": "4",
    "unique_customers": "4"
  },
  {
    "customer_state": "SP",
    "customer_city": "embu-guacu",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "12",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "14",
    "total_freight_revenue": "818",
    "total_orders": "57",
    "unique_customers": "46"
  },
  {
    "customer_state": "PR",
    "customer_city": "nova santa rosa",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "13",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "24",
    "total_freight_revenue": "98",
    "total_orders": "4",
    "unique_customers": "4"
  },
  {
    "customer_state": "SP",
    "customer_city": "areiopolis",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "13",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "16",
    "total_freight_revenue": "48",
    "total_orders": "3",
    "unique_customers": "3"
  },
  {
    "customer_state": "SP",
    "customer_city": "artur nogueira",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "11",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "16",
    "total_freight_revenue": "774",
    "total_orders": "48",
    "unique_customers": "40"
  },
  {
    "customer_state": "PR",
    "customer_city": "nova laranjeiras",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "23",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "43",
    "total_freight_revenue": "43",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "santo andre",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "11",
    "on_time_delivery_percentage": "96",
    "avg_freight_cost": "14",
    "total_freight_revenue": "12392",
    "total_orders": "872",
    "unique_customers": "777"
  },
  {
    "customer_state": "SP",
    "customer_city": "balsamo",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "19",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "14",
    "total_freight_revenue": "126",
    "total_orders": "9",
    "unique_customers": "6"
  },
  {
    "customer_state": "SP",
    "customer_city": "santana de parnaiba",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "10",
    "on_time_delivery_percentage": "95",
    "avg_freight_cost": "14",
    "total_freight_revenue": "2836",
    "total_orders": "205",
    "unique_customers": "178"
  },
  {
    "customer_state": "MG",
    "customer_city": "jenipapo de minas",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "18",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "15",
    "total_freight_revenue": "15",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "MG",
    "customer_city": "japaraiba",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "6",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "24",
    "total_freight_revenue": "24",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "bananal",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "12",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "17",
    "total_freight_revenue": "120",
    "total_orders": "7",
    "unique_customers": "5"
  },
  {
    "customer_state": "RS",
    "customer_city": "tapera",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "19",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "17",
    "total_freight_revenue": "17",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "RS",
    "customer_city": "ajuricaba",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "17",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "27",
    "total_freight_revenue": "53",
    "total_orders": "2",
    "unique_customers": "2"
  },
  {
    "customer_state": "SP",
    "customer_city": "barueri",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "10",
    "on_time_delivery_percentage": "95",
    "avg_freight_cost": "15",
    "total_freight_revenue": "7081",
    "total_orders": "469",
    "unique_customers": "419"
  },
  {
    "customer_state": "SC",
    "customer_city": "coronel freitas",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "17",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "19",
    "total_freight_revenue": "19",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "santa lucia",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "14",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "22",
    "total_freight_revenue": "65",
    "total_orders": "3",
    "unique_customers": "3"
  },
  {
    "customer_state": "SP",
    "customer_city": "santa isabel",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "12",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "13",
    "total_freight_revenue": "391",
    "total_orders": "31",
    "unique_customers": "28"
  },
  {
    "customer_state": "CE",
    "customer_city": "erere",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "25",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "38",
    "total_freight_revenue": "38",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "MG",
    "customer_city": "itabirinha",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "12",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "49",
    "total_freight_revenue": "49",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "oriente",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "13",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "14",
    "total_freight_revenue": "58",
    "total_orders": "4",
    "unique_customers": "3"
  },
  {
    "customer_state": "SP",
    "customer_city": "espirito santo do turvo",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "14",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "13",
    "total_freight_revenue": "39",
    "total_orders": "3",
    "unique_customers": "2"
  },
  {
    "customer_state": "SP",
    "customer_city": "braganca paulista",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "11",
    "on_time_delivery_percentage": "98",
    "avg_freight_cost": "16",
    "total_freight_revenue": "2556",
    "total_orders": "160",
    "unique_customers": "144"
  },
  {
    "customer_state": "RS",
    "customer_city": "caibate",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "23",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "20",
    "total_freight_revenue": "20",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "osasco",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "10",
    "on_time_delivery_percentage": "96",
    "avg_freight_cost": "14",
    "total_freight_revenue": "11628",
    "total_orders": "831",
    "unique_customers": "724"
  },
  {
    "customer_state": "SP",
    "customer_city": "fernando prestes",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "13",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "15",
    "total_freight_revenue": "105",
    "total_orders": "7",
    "unique_customers": "6"
  },
  {
    "customer_state": "SP",
    "customer_city": "sud mennucci",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "14",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "14",
    "total_freight_revenue": "70",
    "total_orders": "5",
    "unique_customers": "5"
  },
  {
    "customer_state": "SP",
    "customer_city": "caieiras",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "11",
    "on_time_delivery_percentage": "96",
    "avg_freight_cost": "15",
    "total_freight_revenue": "1523",
    "total_orders": "101",
    "unique_customers": "97"
  },
  {
    "customer_state": "MG",
    "customer_city": "dionisio",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "19",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "18",
    "total_freight_revenue": "36",
    "total_orders": "2",
    "unique_customers": "2"
  },
  {
    "customer_state": "MG",
    "customer_city": "desterro do melo",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "8",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "11",
    "total_freight_revenue": "11",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "mogi mirim",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "11",
    "on_time_delivery_percentage": "99",
    "avg_freight_cost": "14",
    "total_freight_revenue": "1141",
    "total_orders": "84",
    "unique_customers": "75"
  },
  {
    "customer_state": "RS",
    "customer_city": "barao",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "24",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "26",
    "total_freight_revenue": "26",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "MG",
    "customer_city": "conceicao das alagoas",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "16",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "33",
    "total_freight_revenue": "99",
    "total_orders": "3",
    "unique_customers": "3"
  },
  {
    "customer_state": "PR",
    "customer_city": "doutor ulysses",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "19",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "18",
    "total_freight_revenue": "37",
    "total_orders": "2",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "trabiju",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "11",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "20",
    "total_freight_revenue": "20",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "BA",
    "customer_city": "jussiape",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "27",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "17",
    "total_freight_revenue": "17",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "franco da rocha",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "11",
    "on_time_delivery_percentage": "99",
    "avg_freight_cost": "15",
    "total_freight_revenue": "1757",
    "total_orders": "114",
    "unique_customers": "108"
  },
  {
    "customer_state": "SP",
    "customer_city": "taboao da serra",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "10",
    "on_time_delivery_percentage": "96",
    "avg_freight_cost": "14",
    "total_freight_revenue": "4560",
    "total_orders": "322",
    "unique_customers": "284"
  },
  {
    "customer_state": "MG",
    "customer_city": "cedro do abaete",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "16",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "15",
    "total_freight_revenue": "15",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "carapicuiba",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "10",
    "on_time_delivery_percentage": "94",
    "avg_freight_cost": "13",
    "total_freight_revenue": "4931",
    "total_orders": "366",
    "unique_customers": "316"
  },
  {
    "customer_state": "SP",
    "customer_city": "gabriel monteiro",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "6",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "14",
    "total_freight_revenue": "14",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "PR",
    "customer_city": "cruzeiro do oeste",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "16",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "20",
    "total_freight_revenue": "157",
    "total_orders": "8",
    "unique_customers": "7"
  },
  {
    "customer_state": "SP",
    "customer_city": "gastao vidigal",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "13",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "22",
    "total_freight_revenue": "67",
    "total_orders": "3",
    "unique_customers": "3"
  },
  {
    "customer_state": "MG",
    "customer_city": "camacho",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "17",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "21",
    "total_freight_revenue": "21",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "MG",
    "customer_city": "cachoeira dourada",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "24",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "23",
    "total_freight_revenue": "23",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "MG",
    "customer_city": "virgolandia",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "26",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "17",
    "total_freight_revenue": "33",
    "total_orders": "2",
    "unique_customers": "2"
  },
  {
    "customer_state": "SP",
    "customer_city": "rubiacea",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "25",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "16",
    "total_freight_revenue": "31",
    "total_orders": "2",
    "unique_customers": "2"
  },
  {
    "customer_state": "MG",
    "customer_city": "bela vista de minas",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "8",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "15",
    "total_freight_revenue": "15",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "RS",
    "customer_city": "glorinha",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "17",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "17",
    "total_freight_revenue": "34",
    "total_orders": "2",
    "unique_customers": "2"
  },
  {
    "customer_state": "BA",
    "customer_city": "muritiba",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "22",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "63",
    "total_freight_revenue": "63",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "ubirajara",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "13",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "16",
    "total_freight_revenue": "16",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "rio grande da serra",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "12",
    "on_time_delivery_percentage": "96",
    "avg_freight_cost": "16",
    "total_freight_revenue": "408",
    "total_orders": "26",
    "unique_customers": "25"
  },
  {
    "customer_state": "SP",
    "customer_city": "taguai",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "14",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "15",
    "total_freight_revenue": "166",
    "total_orders": "11",
    "unique_customers": "10"
  },
  {
    "customer_state": "RJ",
    "customer_city": "sacra familia do tingua",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "20",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "29",
    "total_freight_revenue": "29",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "rinopolis",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "15",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "15",
    "total_freight_revenue": "30",
    "total_orders": "2",
    "unique_customers": "2"
  },
  {
    "customer_state": "SP",
    "customer_city": "pedranopolis",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "9",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "15",
    "total_freight_revenue": "15",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "MG",
    "customer_city": "alpercata",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "19",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "16",
    "total_freight_revenue": "32",
    "total_orders": "2",
    "unique_customers": "2"
  },
  {
    "customer_state": "MG",
    "customer_city": "agua comprida",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "17",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "17",
    "total_freight_revenue": "34",
    "total_orders": "2",
    "unique_customers": "2"
  },
  {
    "customer_state": "RJ",
    "customer_city": "engenheiro passos",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "21",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "20",
    "total_freight_revenue": "40",
    "total_orders": "2",
    "unique_customers": "2"
  },
  {
    "customer_state": "SP",
    "customer_city": "vargem grande paulista",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "11",
    "on_time_delivery_percentage": "96",
    "avg_freight_cost": "15",
    "total_freight_revenue": "734",
    "total_orders": "48",
    "unique_customers": "43"
  },
  {
    "customer_state": "PR",
    "customer_city": "alto piquiri",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "14",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "21",
    "total_freight_revenue": "21",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "holambra",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "16",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "15",
    "total_freight_revenue": "383",
    "total_orders": "26",
    "unique_customers": "23"
  },
  {
    "customer_state": "SP",
    "customer_city": "iaras",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "10",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "14",
    "total_freight_revenue": "14",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "ibira",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "12",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "15",
    "total_freight_revenue": "90",
    "total_orders": "6",
    "unique_customers": "6"
  },
  {
    "customer_state": "SP",
    "customer_city": "indiana",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "13",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "15",
    "total_freight_revenue": "45",
    "total_orders": "3",
    "unique_customers": "3"
  },
  {
    "customer_state": "SP",
    "customer_city": "itapevi",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "11",
    "on_time_delivery_percentage": "94",
    "avg_freight_cost": "14",
    "total_freight_revenue": "2803",
    "total_orders": "195",
    "unique_customers": "170"
  },
  {
    "customer_state": "AL",
    "customer_city": "porto de pedras",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "18",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "20",
    "total_freight_revenue": "20",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "MG",
    "customer_city": "sao domingos das dores",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "16",
    "on_time_delivery_percentage": "100",
    "avg_freight_cost": "13",
    "total_freight_revenue": "13",
    "total_orders": "1",
    "unique_customers": "1"
  },
  {
    "customer_state": "SP",
    "customer_city": "itatiba",
    "avg_delivery_time_days": "7",
    "avg_days_early_positive_late_negative": "11",
    "on_time_delivery_percentage": "99",
    "avg_freight_cost": "15",
    "total_fr